# Email SPAM Filtering using logistic regression


In [ ]:
import numpy as np                  #imports maths , speacilly we get nd arrays (multi (n) dimensional arrays) 
import seaborn as sns                                    #these array are highly optimized for numerical operations
import pandas as pd 
from sklearn.model_selection import train_test_split  #used to bring ml support to the code
                                                      #utility of sciket learn, used to split the data into training and testing dataset
from sklearn.feature_extraction.text import CountVectorizer #used to convert text into numbers
from sklearn.feature_extraction.text import TfidfVectorizer #used to convert text into numbers
from sklearn.linear_model import LogisticRegression #used to predict the probability of a categorical dependent variable , suitable for binary classification
from sklearn.metrics import accuracy_score #used to check the accuracy of the model




ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

ImportError: numpy._core.multiarray failed to import

In [535]:
df = pd.read_csv('email.csv') #reading the csv file 
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [536]:
data = df.where((pd.notnull(df)),'') #replacing the null values with a null string
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [537]:
df.info() #gives the information about the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [538]:
data.shape#gives the shape of the data

(5572, 2)

In [539]:
data.loc[data['Category']=='spam','Category',]=0 #replacing spam with 0
data.loc[data['Category']=='ham','Category',]=1 #replacing ham with 1


In [540]:
X=data['Message'] #assigning the message column to X
Y=data['Category'] #assigning the category column to Y

In [541]:
print(X) 

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object


In [542]:
print(Y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object


In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2, random_state=10) # here 0.2 mean 80/20 dvision testing is 20 80 is training 
# randomness hyperparameter is used to control any randomeness happening in datasets

In [ ]:
print(df.shape)
print (X_train.shape,Y_train.shape) #gives the shape of the training data
print (X_test.shape,Y_test.shape)

(5572, 2)
(4457,) (4457,)


In [545]:
feature_extraction= TfidfVectorizer( min_df=1 ,stop_words = 'english', lowercase= True ) #used to convert the text into numerical representation
# stop word are words that dont add value to the meaning of the sentence
X_train_features= feature_extraction.fit_transform(X_train) #fitting the training data into the feature extraction
Y_train = Y_train.astype('int') #converting the Y_train into integer

X_test_features = feature_extraction.transform(X_test) #fitting the testing data into the feature extraction
Y_test = Y_test.astype('int') #converting the Y_test into integer

In [546]:
print(X_train)

5281               And how you will do that, princess? :)
1300    Great to hear you are settling well. So what's...
5128    Wot about on wed nite I am 3 then but only til 9!
1808      Do have a nice day today. I love you so dearly.
856     Talk sexy!! Make new friends or fall in love i...
                              ...                        
1180                  To day class is there are no class.
3441                       What time you thinkin of goin?
1344    Crazy ar he's married. Ü like gd looking guys ...
4623                They finally came to fix the ceiling.
1289                             Happy new year to u too!
Name: Message, Length: 4457, dtype: object


In [547]:
print(X_train_features)

  (0, 5218)	1.0
  (1, 4745)	0.4534886728220183
  (1, 7266)	0.39349136612703317
  (1, 3213)	0.47563189358898544
  (1, 5831)	0.47563189358898544
  (1, 3258)	0.33769704827191216
  (1, 3117)	0.2702256012963159
  (2, 6650)	0.4724534451200627
  (2, 4618)	0.4798905751162268
  (2, 7168)	0.5655453624599882
  (2, 7324)	0.4760790072128801
  (3, 2111)	0.6471064429181299
  (3, 4078)	0.3578260568100486
  (3, 6689)	0.3660825403036148
  (3, 2099)	0.34395340550548065
  (3, 4599)	0.44821132641606853
  (4, 4264)	0.19400419560355137
  (4, 644)	0.32783379543981434
  (4, 7038)	0.30174250755529963
  (4, 3727)	0.13960291836824296
  (4, 5822)	0.20666960669811668
  (4, 2096)	0.24955993178627037
  (4, 6552)	0.3408280379552965
  (4, 2262)	0.312571370431853
  (4, 7315)	0.312571370431853
  :	:
  (4454, 2701)	0.275356125521126
  (4454, 4208)	0.24725965866005303
  (4454, 2891)	0.2523713079039201
  (4454, 3932)	0.275356125521126
  (4454, 4241)	0.23543228813185407
  (4454, 5234)	0.22427484104284712
  (4454, 1981)	0.226

In [ ]:
print(Y_train)

In [ ]:
print(Y_test)

# `Using Logistic Regression`

In [548]:
model = LogisticRegression() #creating a model
model.fit(X_train_features,Y_train) #fitting the training data into the model



LogisticRegression()

In [ ]:
#predicting the training data
prediction_on_training_data = model.predict(X_train_features) 
prediction_on_training_data

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
prediction_on_test_data = model.predict(X_test_features) #predicting the testing data
print(prediction_on_test_data)

In [ ]:
#checking the accuracy of the training data
accuracy_on_training_data = accuracy_score(Y_train,prediction_on_training_data) 
print ('Accuracy on training data : ', accuracy_on_training_data)

#checking the accuracy of the testing data
accuracy_on_test_data = accuracy_score(Y_test,prediction_on_test_data)
print ('Accuracy on test data : ', accuracy_on_test_data)

Accuracy on training data :  0.97083239847431


# `Using Perceptron `

In [553]:
from sklearn.linear_model import Perceptron
p = Perceptron()

In [554]:
p.fit(X_train_features,Y_train)

Perceptron()

In [555]:
p.coef_

array([[-0.25929118,  0.        ,  0.        , ...,  0.        ,
        -0.22579267,  0.        ]])

In [556]:
p.intercept_

array([0.31])

In [ ]:
perceptron_train_prediction=p.predict(X_train_features)
print(f'Train predictions : {perceptron_train_prediction}')

perceptron_test_prediction=p.predict(X_test_features)
print(f'Test predictions : {perceptron_test_prediction}')

[1 1 1 ... 1 1 1]
[0 1 1 ... 1 1 1]


In [ ]:
print(f"train accuracy : {accuracy_score(Y_train,perceptron_train_prediction)}")
print (f"test accuracy : {accuracy_score(Y_test,perceptron_test_prediction)}")


train accuracy : 1.0
test accuracy : 0.9721973094170404


# `Perceptron using L2 Regularization`

In [566]:
# Initialize the Perceptron model with L2 regularization
g = Perceptron(max_iter=1000, penalty='l2', alpha=0.0002,random_state=42) #did hit and trial to get the best accuracy did for 0.01,0.001,0.0001,0.0002

# Train the model
g.fit(X_train_features, Y_train)

Perceptron(alpha=0.0002, penalty='l2', random_state=42)

In [ ]:
# Make predictions
new_perceptron_train_prediction = g.predict(X_train_features)
new_perceptron_test_prediction = g.predict(X_test_features)

In [ ]:
# Print accuracy scores
print(f"train accuracy: {accuracy_score(Y_train, new_perceptron_train_prediction)}")
print(f"test accuracy: {accuracy_score(Y_test, new_perceptron_test_prediction)}")

train accuracy: 0.982499439084586
test accuracy: 0.9524663677130045


# **`Prediction on Fixed Input`**


In [562]:
input_emails = [
    "join us to celebrate our anniversary. Read the email for member's gift​​.       AW ASUS WebStorage <nano-edge@asuswebstorage.com>           To:You Thu 9/7/2023 1:30 PM   3 DAYS ONLY  1 TB US$1.40/month   Hello! sujalsharma1343  This time last year, or years before, you decided to entrust your files to us, ASUS WebStorage. That would make today our anniversary! On this cherished occasion, we’d like to present to you an exclusive anniversary offer. We extend our sincere thanks for your continued support.  Enjoy! ASUS WebStorage Team  Buy Now *This offer is valid only for ASUS Cloud ID: sujalsharma1343@outlook.com Forgot your password?  If you do not wish to receive any more marketing emails from us, you can opt out by unsubscribing. Copyright © ASUS Cloud Corporation. All rights reserved.",

    "Congratulations! You have been selected to receive a free gift card worth $1000. To claim your gift card, simply click on the link below and enter your personal information. Don't miss out on this amazing offer!",

    "Dear customer, we regret to inform you that your account has been suspended due to suspicious activity. Please click on the link below to verify your account and reactivate it. Thank you for your cooperation.",
    
    "Hello, I am a Nigerian prince and I need your help to transfer $10 million to a foreign bank account. If you help me, I will reward you with a large sum of money. Please reply to this email with your bank account details.",
]
input_email_features = feature_extraction.transform(input_emails)
prediction= model.predict(input_email_features)
print (prediction)
if (prediction[0]==1):
  print('Ham mail')
else:
    print('Spam mail')

[1 0 1 1]
Ham mail


In [563]:
input_emails = [
    "join us to celebrate our anniversary. Read the email for member's gift​​.       AW ASUS WebStorage <nano-edge@asuswebstorage.com>           To:You Thu 9/7/2023 1:30 PM   3 DAYS ONLY  1 TB US$1.40/month   Hello! sujalsharma1343  This time last year, or years before, you decided to entrust your files to us, ASUS WebStorage. That would make today our anniversary! On this cherished occasion, we’d like to present to you an exclusive anniversary offer. We extend our sincere thanks for your continued support.  Enjoy! ASUS WebStorage Team  Buy Now *This offer is valid only for ASUS Cloud ID: sujalsharma1343@outlook.com Forgot your password?  If you do not wish to receive any more marketing emails from us, you can opt out by unsubscribing. Copyright © ASUS Cloud Corporation. All rights reserved.",
    "Congratulations! You have been selected to receive a free gift card worth $1000. To claim your gift card, simply click on the link below and enter your personal information. Don't miss out on this amazing offer!",
    "Dear customer, we regret to inform you that your account has been suspended due to suspicious activity. Please click on the link below to verify your account and reactivate it. Thank you for your cooperation.",
    "Hello, I am a Nigerian prince and I need your help to transfer $10 million to a foreign bank account. If you help me, I will reward you with a large sum of money. Please reply to this email with your bank account details.",
]
input_email_features = feature_extraction.transform(input_emails)
perceptron_pred=p.predict(input_email_features)
print(perceptron_pred)

[1 0 1 1]


In [564]:
input_emails = [
    "join us to celebrate our anniversary. Read the email for member's gift​​.       AW ASUS WebStorage <nano-edge@asuswebstorage.com>           To:You Thu 9/7/2023 1:30 PM   3 DAYS ONLY  1 TB US$1.40/month   Hello! sujalsharma1343  This time last year, or years before, you decided to entrust your files to us, ASUS WebStorage. That would make today our anniversary! On this cherished occasion, we’d like to present to you an exclusive anniversary offer. We extend our sincere thanks for your continued support.  Enjoy! ASUS WebStorage Team  Buy Now *This offer is valid only for ASUS Cloud ID: sujalsharma1343@outlook.com Forgot your password?  If you do not wish to receive any more marketing emails from us, you can opt out by unsubscribing. Copyright © ASUS Cloud Corporation. All rights reserved.",
    "Congratulations! You have been selected to receive a free gift card worth $1000. To claim your gift card, simply click on the link below and enter your personal information. Don't miss out on this amazing offer!",
    "Dear customer, we regret to inform you that your account has been suspended due to suspicious activity. Please click on the link below to verify your account and reactivate it. Thank you for your cooperation.",
    "Hello, I am a Nigerian prince and I need your help to transfer $10 million to a foreign bank account. If you help me, I will reward you with a large sum of money. Please reply to this email with your bank account details.",
]
input_email_features = feature_extraction.transform(input_emails)
perceptron_pred=g.predict(input_email_features)
print(perceptron_pred)

[1 0 0 1]


# **`Prediction on User Input`**


In [565]:
input_emails = input("Enter the email: ")  #input the email text that you want to check for 
input_email_features = feature_extraction.transform([input_emails]) #transforming the input email into numerical representation
prediction= model.predict(input_email_features)
print (prediction)
if (prediction[0]==1):
  print('Ham mail')
else:
    print('Spam mail')

[1]
Ham mail
